languageCode = "en"
languageName = "English"
weight = 1
title = "JohnSilva"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "pp-modified.png"
   secondaryLogo = "pp.png"
   description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Eloi Couderc"
  email = "eloi.couderc@epita.fr"
  image = "pp.png"
  headline = "Engineering student at EPITA"
  bio = ""
  links = [ { email = "mailto:john@designproworks.com" },
     { link = "https://themes.gohugo.io/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
     { facebook = "https://www.facebook.com/profile.php?id=61566421582008" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { github = "https://github.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
     { instagram = "https://instagram.com/john_desilva" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://linkedin.com/in/john-de-silva-a1836b1b4" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
     { snapchat = "https://snapchat.com/add/johndesilva2020" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
     { telegram = "https://t.me/@designproworks" },
     { threads = "https://www.threads.net/@john_desilva" },
     { tiktok = "https://tiktok.com/@johnwick9502" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
     { x-twitter = "https://twitter.com/@john1silva" },
     { whatsapp = "https://wa.me/+19053997203" },
     { youtube = "https://youtube.com/@designproworks" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},

   ]
